// =============================================================================
// mul_agent_cfg.sv  (part of mul_agent_pkg)
// -----------------------------------------------------------------------------
// Configuration object of the MUL agent. The agent is passive by design
// (tb_architecture/arch.jpg: "MUL agent" = Monitor only, no sequencer, no
// driver) - stimulus reaches the multiplier only through the instruction
// stream generated by the Instructions agent.
// =============================================================================
class mul_agent_cfg extends uvm_object;

  // Virtual interface. Set by the env / test, or resolved by the agent from
  // uvm_config_db key "alu_mul_vif" (published by alu_mul_bind.sv).
  virtual alu_mul_if vif;

  // Always UVM_PASSIVE. Kept as a field so the agent can report a mistake in
  // the env configuration instead of silently ignoring it.
  uvm_active_passive_enum is_active = UVM_PASSIVE;

  // Monitor-level sanity checks (uvm_error): illegal operator encoding for
  // RV32IM, alu_en together with mult_en, operands changing while the
  // instruction is in EX, mult_en dropping before ex_valid, hang detector.
  bit check_protocol = 1;

  // Hang detector: a MUL-unit instruction must complete within this many
  // cycles in EX. The multiplier itself needs at most MULH_LATENCY (5) cycles;
  // everything beyond that is an LSU/WB stall (data-side wait states). Raise
  // it if the Data agent is configured with very long response delays.
  int unsigned max_cycles_in_ex = 64;

  // Attach pc/instr from the ID issue pulse to every transaction.
  bit tag_enable = 1;

  // Print every completed transaction at UVM_HIGH.
  bit verbose = 0;

  `uvm_object_utils_begin(mul_agent_cfg)
    `uvm_field_enum(uvm_active_passive_enum, is_active, UVM_ALL_ON)
    `uvm_field_int (check_protocol,    UVM_ALL_ON)
    `uvm_field_int (max_cycles_in_ex,  UVM_ALL_ON | UVM_DEC)
    `uvm_field_int (tag_enable,        UVM_ALL_ON)
    `uvm_field_int (verbose,           UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "mul_agent_cfg");
    super.new(name);
  endfunction

endclass : mul_agent_cfg
